package com.example.cooking_app.Activity;

import androidx.appcompat.app.AppCompatActivity;
import androidx.constraintlayout.widget.ConstraintLayout;

import android.annotation.SuppressLint;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;

import com.example.cooking_app.Database.DBHandler;
import com.example.cooking_app.R;

public class WelcomeActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_welcome);
        Button btnStart = findViewById(R.id.btnStart);
        btnStart.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(WelcomeActivity.this, SignInActivity.class);
                startActivity(intent);
            }
        });

        DBHandler dbHandler = new DBHandler(this);

//        dbHandler.addCategory("Món ăn miền Bắc");
//        dbHandler.addCategory("Món ăn miền Trung");
//        dbHandler.addCategory("Món ăn miền Nam");
//        dbHandler.addRecipe("Thịt lợn kho","anh2","60 phút", "1");
//        dbHandler.addRecipe("Thịt gà kho","anh3","70 phút", "2");
//        dbHandler.addRecipe("Thịt bò kho","anh4","80 phút", "3");
//        dbHandler.addRecipe("Thịt cá kho","dessert_orange_food_chocolate","90 phút", "4");
//        dbHandler.addRecipe("Gà xào sả ớt","ga_xao_xa_ot","15 phút", "4");
//        dbHandler.addRecipe("Canh chua cá lóc","caloc","30 phút", "4");
//        dbHandler.addRecipe("Khổ qua nhồi thịt","kho_qua_nhoi_thit","30 phút", "5");
//        dbHandler.addRecipe("Canh trứng nấu cà chua","canh_trung_ca_chua","10 phút", "5");
//        dbHandler.addRecipe("Canh gà với lá giang","canh_ga_la_giang","40 phút", "6");
//        dbHandler.addRecipe("Canh bí đao nấu với xương","canh_bi_dao_nau_xuong","30 phút", "6");
//
//        dbHandler.addRecipeCategory(1,1);
//        dbHandler.addRecipeCategory(2,2);
//        dbHandler.addRecipeCategory(3,3);
//        dbHandler.addRecipeCategory(1,4);
//        dbHandler.addRecipeCategory(1,5);
//        dbHandler.addRecipeCategory(2,6);
//        dbHandler.addRecipeCategory(3,7);
//        dbHandler.addRecipeCategory(1,8);
//        dbHandler.addRecipeCategory(2,9);
//        dbHandler.addRecipeCategory(1,10);
//
//        dbHandler.addIngredient("Thịt heo");
//        dbHandler.addIngredient("Hành tím");
//        dbHandler.addIngredient("Tỏi");
//        dbHandler.addIngredient("Hành lá");
//        dbHandler.addIngredient("Ớt");
//        dbHandler.addIngredient("Đường");
//        dbHandler.addIngredient("Muối");
//        dbHandler.addIngredient("Bột ngọt");
//        dbHandler.addIngredient("Hạt nêm");
//        dbHandler.addIngredient("Nước mắm");
//        dbHandler.addIngredient("Dầu ăn");
//        dbHandler.addIngredient("Tiêu");
//        dbHandler.addIngredient("Cá");
//        dbHandler.addIngredient("Nước dừa");
//        dbHandler.addIngredient("Gừng");
//        dbHandler.addIngredient("Giấm");
//        dbHandler.addIngredient("Ức gà");
//        dbHandler.addIngredient("Thịt bò");
//        dbHandler.addIngredient("Sả");
//        dbHandler.addIngredient("Tương ớt");
//        dbHandler.addIngredient("Thịt gà");
//        dbHandler.addIngredient("Hành tây");
//        dbHandler.addIngredient("Tỏi");
//        dbHandler.addIngredient("Nước màu");
//        dbHandler.addIngredient("Bột nêm");
//        dbHandler.addIngredient("Cá lóc");
//        dbHandler.addIngredient("Rau muống");
//        dbHandler.addIngredient("Cà chua");
//        dbHandler.addIngredient("Quả me chín");
//        dbHandler.addIngredient("Củ cải đắng");
//        dbHandler.addIngredient("Trái dấm tươi");
//        dbHandler.addIngredient("Nước lọc");
//        dbHandler.addIngredient("Rau thơm");
//        dbHandler.addIngredient("Khổ qua");
//        dbHandler.addIngredient("Tôm");
//        dbHandler.addIngredient("Trứng gà");
//        dbHandler.addIngredient("Trứng vịt");
//        dbHandler.addIngredient("Lá giang");
//        dbHandler.addIngredient("Cà rốt");
//        dbHandler.addIngredient("Quả bầu");
//        dbHandler.addIngredient("Con hến");
//        dbHandler.addIngredient("Xương heo");
//        dbHandler.addIngredient("Xương gà");
//        dbHandler.addIngredient("Bí đao");
//        dbHandler.addIngredient("Cua");
//
//        dbHandler.addRecipeIngredient(1,1,"400g");
//        dbHandler.addRecipeIngredient(1,2,"");
//        dbHandler.addRecipeIngredient(1,3,"");
//        dbHandler.addRecipeIngredient(1,4,"");
//        dbHandler.addRecipeIngredient(1,5,"");
//        dbHandler.addRecipeIngredient(1,6,"");
//        dbHandler.addRecipeIngredient(1,7,"");
//        dbHandler.addRecipeIngredient(1,8,"");
//        dbHandler.addRecipeIngredient(1,9,"");
//        dbHandler.addRecipeIngredient(1,10,"");
//        dbHandler.addRecipeIngredient(1,11,"");
//        dbHandler.addRecipeIngredient(1,12,"");
//        dbHandler.addRecipeIngredient(4,1,"100g");
//        dbHandler.addRecipeIngredient(4,13,"400g");
//        dbHandler.addRecipeIngredient(4,14,"150ml");
//        dbHandler.addRecipeIngredient(4,2,"");
//        dbHandler.addRecipeIngredient(4,4,"");
//        dbHandler.addRecipeIngredient(4,15,"");
//        dbHandler.addRecipeIngredient(4,3,"");
//        dbHandler.addRecipeIngredient(4,5,"");
//        dbHandler.addRecipeIngredient(4,10,"");
//        dbHandler.addRecipeIngredient(4,11,"");
//        dbHandler.addRecipeIngredient(4,16,"");
//        dbHandler.addRecipeIngredient(4,12,"");
//        dbHandler.addRecipeIngredient(2,17,"300g");
//        dbHandler.addRecipeIngredient(2,12,"");
//        dbHandler.addRecipeIngredient(2,3,"");
//        dbHandler.addRecipeIngredient(2,5,"");
//        dbHandler.addRecipeIngredient(2,4,"");
//        dbHandler.addRecipeIngredient(2,10,"");
//        dbHandler.addRecipeIngredient(2,11,"");
//        dbHandler.addRecipeIngredient(2,16,"");
//        dbHandler.addRecipeIngredient(2,6,"");
//        dbHandler.addRecipeIngredient(2,8,"");
//        dbHandler.addRecipeIngredient(2,9,"");
//        dbHandler.addRecipeIngredient(3,18,"400g");
//        dbHandler.addRecipeIngredient(3,12,"");
//        dbHandler.addRecipeIngredient(3,11,"");
//        dbHandler.addRecipeIngredient(3,2,"");
//        dbHandler.addRecipeIngredient(3,3,"");
//        dbHandler.addRecipeIngredient(3,5,"");
//        dbHandler.addRecipeIngredient(3,19,"");
//        dbHandler.addRecipeIngredient(3,20,"");
//        dbHandler.addRecipeIngredient(3,9,"");
//        dbHandler.addRecipeIngredient(5,21,"400g");
//        dbHandler.addRecipeIngredient(5,19,"2");
//        dbHandler.addRecipeIngredient(5,5,"");
//        dbHandler.addRecipeIngredient(5,23,"");
//        dbHandler.addRecipeIngredient(5,6,"");
//        dbHandler.addRecipeIngredient(5,10,"");
//        dbHandler.addRecipeIngredient(5,24,"");
//        dbHandler.addRecipeIngredient(5,25,"");
//        dbHandler.addRecipeIngredient(5,7,"");
//        dbHandler.addRecipeIngredient(5,11,"");
//        dbHandler.addRecipeIngredient(6,26,"500g");
//        dbHandler.addRecipeIngredient(6,27,"");
//        dbHandler.addRecipeIngredient(6,28,"");
//        dbHandler.addRecipeIngredient(6,5,"");
//        dbHandler.addRecipeIngredient(6,29,"");
//        dbHandler.addRecipeIngredient(6,30,"");
//        dbHandler.addRecipeIngredient(6,2,"");
//        dbHandler.addRecipeIngredient(6,31,"");
//        dbHandler.addRecipeIngredient(6,32,"");
//        dbHandler.addRecipeIngredient(6,6,"");
//        dbHandler.addRecipeIngredient(6,7,"");
//        dbHandler.addRecipeIngredient(7,34,"");
//        dbHandler.addRecipeIngredient(7,1,"");
//        dbHandler.addRecipeIngredient(7,2,"");
//        dbHandler.addRecipeIngredient(7,32,"");
//        dbHandler.addRecipeIngredient(7,6,"");
//        dbHandler.addRecipeIngredient(7,7,"");
//        dbHandler.addRecipeIngredient(7,9,"");
//        dbHandler.addRecipeIngredient(7,33,"");
//        dbHandler.addRecipeIngredient(8,36,"");
//        dbHandler.addRecipeIngredient(8,28,"");
//        dbHandler.addRecipeIngredient(8,2,"");
//        dbHandler.addRecipeIngredient(8,32,"");
//        dbHandler.addRecipeIngredient(8,23,"");
//        dbHandler.addRecipeIngredient(8,32,"");
//        dbHandler.addRecipeIngredient(8,9,"");
//        dbHandler.addRecipeIngredient(8,6,"");
//        dbHandler.addRecipeIngredient(8,7,"");
//        dbHandler.addRecipeIngredient(8,12,"");
//        dbHandler.addRecipeIngredient(8,33,"");
//        dbHandler.addRecipeIngredient(9,21,"");
//        dbHandler.addRecipeIngredient(9,38,"");
//        dbHandler.addRecipeIngredient(9,2,"");
//        dbHandler.addRecipeIngredient(9,39,"");
//        dbHandler.addRecipeIngredient(9,32,"");
//        dbHandler.addRecipeIngredient(9,9,"");
//        dbHandler.addRecipeIngredient(9,6,"");
//        dbHandler.addRecipeIngredient(9,7,"");
//        dbHandler.addRecipeIngredient(9,12,"");
//        dbHandler.addRecipeIngredient(9,33,"");
//        dbHandler.addRecipeIngredient(10,40,"");
//        dbHandler.addRecipeIngredient(10,41,"");
//        dbHandler.addRecipeIngredient(10,2,"");
//        dbHandler.addRecipeIngredient(10,23,"");
//        dbHandler.addRecipeIngredient(10,32,"");
//        dbHandler.addRecipeIngredient(10,9,"");
//        dbHandler.addRecipeIngredient(10,6,"");
//        dbHandler.addRecipeIngredient(10,7,"");
//        dbHandler.addRecipeIngredient(10,12,"");
//        dbHandler.addRecipeIngredient(10,33,"");
//
//
//        dbHandler.addInstruction(1,1,"Rửa sạch thịt heo với nước sạch, sau đó cắt thành từng miếng vừa ăn. Với món này bạn có thể sử dụng thịt ba chỉ hay thịt nạc đều ngon.");
//        dbHandler.addInstruction(1,2,"Hành tím và tỏi lột vỏ, rồi cắt lát mỏng, nếu thích bạn cũng có thể băm nhuyễn cũng được nha.");
//        dbHandler.addInstruction(1,3,"Hành lá và ớt rửa sạch, hành lá thì cắt nhỏ, ớt bạn có thể để nguyên trái hoặc cắt nhỏ tùy theo sở thích ăn cay của mình.");
//        dbHandler.addInstruction(1,4,"Cho thịt heo vào một cái tô cùng với một ít nước mắm, đường, hạt nêm, tiêu và muối, trộn đều rồi ướp trong 15 phút cho thịt thấm gia vị. Để thịt lên màu đẹp hơn thì bạn nên sử dụng đường vàng khi kho nhé.");
//        dbHandler.addInstruction(1,5,"Bắc một cái chảo lên bếp, sau đó cho dầu ăn và một ít đường vào, đảo đều ở lửa nhỏ cho đường tan, chuyển thành màu vàng nâu là được.");
//        dbHandler.addInstruction(1,6,"Sau đó cho hành tím và tỏi vào, phi lên cho thơm, rồi cho thịt heo vào, đảo trong 5 phút để thịt ngấm gia vị và đều màu.");
//        dbHandler.addInstruction(1,7,"Tiếp đó cho nước vào sâm sấp mặt thịt, kho ở lửa vừa cho thịt chín mềm, nước kho sệt lại theo ý thích thì tắt bếp.");
//        dbHandler.addInstruction(1,8,"Rắc lên một ít tiêu, hành lá và ớt, vậy là món thịt kho tộ đã xong rồi đó, cho ra bàn ăn và thưởng thức ngay thôi.");
//        dbHandler.addInstruction(2,1,"Lấy khoảng 3 nhánh tiêu, lượng tiêu tương đương với 1 muỗng canh tiêu xanh. Gỡ hết tất cả hạt tiêu xanh ra khỏi cuống và giã dập.");
//        dbHandler.addInstruction(2,2,"Hành lá cắt khúc vừa ăn. Tỏi băm nhỏ. Ớt cắt thành khoanh vừa ăn.");
//        dbHandler.addInstruction(2,3,"Để khử mùi hôi, thịt gà mua về nhổ lông cho sạch. Trộn 1 ít giấm và muối rồi xoa đều lên khắp phần thịt gà rồi rửa lại bằng nước sạch.");
//        dbHandler.addInstruction(2,4,"Cắt thành những miếng vuông vừa ăn có kích thước cỡ 1 đốt ngón tay, để ráo.");
//        dbHandler.addInstruction(2,5,"Ướp thịt gà với 1/2 muỗng cà phê muối, 1/2 muỗng cà phê bột ngọt, 1/2 muỗng cà phê hạt nêm, 2 muỗng cà phê đường, 3 muỗng canh nước mắm, 1 muỗng canh nước màu, 1 muỗng canh tiêu hạt giã dập.");
//        dbHandler.addInstruction(2,6,"Trộn đều và để khoảng 20 - 30 phút để thịt gà ngấm đều gia vị.");
//        dbHandler.addInstruction(2,7,"Bắc 1 cái chảo lên bếp. Cho vào 2 muỗng canh dầu ăn. Khi dầu nóng thì cho phần tỏi băm vào phi thơm, cho đến khi tỏi bắt đầu chuyển màu vàng.");
//        dbHandler.addInstruction(2,8,"Lúc này, bạn cho gà vào xào trong khoảng 5 phút để gà bắt đầu săn lại và chín.");
//        dbHandler.addInstruction(2,9,"Tiếp theo, bạn cho nửa chén nước vào, hạ lửa nhỏ, tiếp tục kho đến khi nước kho bắt đầu sệt lại.");
//        dbHandler.addInstruction(2,10,"Tiếp theo, bạn cho 5 nhánh tiêu xanh và ớt cắt khoanh vào kho khoảng 2 - 3 phút là gà chín, rắc hành lá lên rồi tắt bếp.");
//        dbHandler.addInstruction(2,11,"Món gà kho tiêu vàng óng đẹp mắt, thịt gà thơm phức quyện cùng vị cay nồng của tiêu xanh là một lựa chọn hoàn hảo cho những ngày mưa lạnh đấy!");
//        dbHandler.addInstruction(3,1,"Bạn ngâm thịt bò trong nước muối loãng tầm 10 phút, sau đó vớt thịt ra, rửa lại thêm 2 - 3 lần nước nữa rồi dùng khăn sạch thấm khô thịt bò.");
//        dbHandler.addInstruction(3,2,"Khi thịt đã ráo nước, bạn cắt thịt thành từng lát dài có độ dày 3cm rồi tiếp tục thái nhỏ thịt thành từng miếng vuông vừa ăn.");
//        dbHandler.addInstruction(3,3,"Bạn cho vào chảo 20ml dầu ăn, khi dầu nóng, bạn cho toàn bộ hành tím, tỏi, ớt và sả đã được băm nhuyễn vào và phi thơm.");
//        dbHandler.addInstruction(3,4,"Khi các nguyên liệu đã vàng, bạn cho 50gr sốt tiêu, 50gr tương ớt, 60ml nước cùng 5gr hạt nêm vào khuấy đều trên lửa vừa cho đến khi hỗn hợp sánh lại.");
//        dbHandler.addInstruction(3,5,"Khi nước sốt đã có độ sệt hoàn hảo, bạn cho thịt bò vào và đảo đều để thịt săn lại. Tiếp đến, bạn cho 30gr hạt tiêu xanh vào, dùng vá trộn đều để các nguyên liệu hòa quyện vào nhau.");
//        dbHandler.addInstruction(3,6,"Cuối cùng, bạn đậy nắp, rim thịt bò trên lửa vừa trong 15 phút cho đến khi thịt bò chín mềm là được.");
//        dbHandler.addInstruction(3,7,"Thịt vai bò với phần nạc mềm, có thêm chút gân sần sật, lại đậm đà, thấm vị, kết hợp với tiêu xanh thơm lừng, có chút ớt hiểm cay cay ăn cùng với cơm nóng quả thật là không thể chê vào đâu được.");
//        dbHandler.addInstruction(4,1,"Khử bớt mùi tanh của cá bằng cách làm sạch. Rửa cá với hỗn hợp nước muối loãng pha thêm một chút giấm và gừng băm nhỏ, sau đó rửa sạch lại dưới vòi nước và để ráo.");
//        dbHandler.addInstruction(4,2,"Cắt cá thành từng khúc nhỏ.");
//        dbHandler.addInstruction(4,3,"Thịt lợn rửa sạch, để ráo nước, thái thành từng miếng nhỏ vừa ăn.");
//        dbHandler.addInstruction(4,4,"Hành khô bóc vỏ, rửa sạch. Chia 2 nửa, 1 nửa băm nhỏ, 1 nửa cắt đôi.");
//        dbHandler.addInstruction(4,5,"Tỏi bóc vỏ, rửa sạch, băm nhỏ");
//        dbHandler.addInstruction(4,6,"Bắc nồi lên bếp, cho một chút dầu ăn cùng hành khô băm và tỏi băm vào phi vàng, dậy mùi thơm.");
//        dbHandler.addInstruction(4,7,"Cho thịt lợn ba chỉ vào đảo đều đến khi thịt săn lại. Sau đó xếp cá vào nồi, thêm hành khô cắt miếng và hành lá. Ở bước này, nếu muốn ăn cay bạn có thể cho thêm ớt tươi, hạt tiêu vào kho cùng.");
//        dbHandler.addInstruction(5,1,"Sả, ớt đem cắt miếng thật mỏng.");
//        dbHandler.addInstruction(5,2,"Hành, tỏi bóc vỏ rồi băm nhuyễn.");
//        dbHandler.addInstruction(5,3,"Cho thịt gà vào tô ướp với một muỗng nước mắm, bột nêm, tiếp đó đảo đều để gà ngấm đều gia vị.");
//        dbHandler.addInstruction(5,4,"Cho một muỗng dầu ăn vào chảo, đợi dầu nóng rồi cho hành tỏi vào phi thơm. Sau đó thêm sả, ớt vào xào lên.");
//        dbHandler.addInstruction(5,5,"Khi thấy thịt săn lại thì thêm ½ muống canh đường, một muỗng canh nước màu với ít nước và chảo");
//        dbHandler.addInstruction(5,6,"Tiếp tục đun với lửa nhỏ đến khi cạn bớt nước thì tắt bếp.");
//        dbHandler.addInstruction(6,1,"Rửa sạch cá, cắt miếng vừa, ướp đường, muối, hạt nêm, bột ngọt khoảng 15 phút.");
//        dbHandler.addInstruction(6,2,"Rửa sạch rau muống, cắt khúc vừa, cà chua và ớt băm nhỏ, cải đắng băm nhuyễn.");
//        dbHandler.addInstruction(6,3,"Cho nước vào nồi đun sôi, cho cá vào nấu trong khoảng 5 phút.");
//        dbHandler.addInstruction(6,4,"Cho hành tím vào phi thơm, sau đó cho cải đắng vào xào vài phút");
//        dbHandler.addInstruction(6,5,"Cho cà chua và ớt vào xào chung với cải đắng.");
//        dbHandler.addInstruction(6,6,"Sau khi cá đã chín, cho rau muống vào nồi và đun thêm 2-3 phút cho rau chín mềm.");
//        dbHandler.addInstruction(6,7,"Thêm quả me vào nồi, đun thêm 1-2 phút cho me vài phút thấm gia vị và canh sôi lại.");
//        dbHandler.addInstruction(6,8,"Nêm thêm đường, muối, hạt nêm để hương vị thêm đậm đà và thêm trái giấm tươi để làm cho canh chua có hương vị thơm ngon");
//        dbHandler.addInstruction(6,9,"Tắt bếp, cho rau thơm vào trộn đều và tận hưởng món canh chua cá lóc nóng cùng cơm trắng.");
//        dbHandler.addInstruction(7,1,"Rửa sạch khổ qua, bổ ra làm đôi, lấy thớ phần ruột bỏ đi");
//        dbHandler.addInstruction(7,2,"Rửa sạch thịt heo hoặc tôm, cắt nhỏ hoặc băm nhuyễn. Nhồi thịt vào bên trong quả mướp đắng");
//        dbHandler.addInstruction(7,3,"Tiếp theo, cho khổ qua vào nồi, đun sôi trong vài phút.");
//        dbHandler.addInstruction(7,4,"Nêm muối, đường, hạt nêm cho vừa ăn.");
//        dbHandler.addInstruction(7,5,"Khi khổ qua đã chín, tắt bếp và cho rau thơm vào canh");
//        dbHandler.addInstruction(8,1,"Rửa sạch trứng và cà chua, cắt cà chua thành những miếng nhỏ");
//        dbHandler.addInstruction(8,2,"Băm nhuyễn hành tím và tỏi.");
//        dbHandler.addInstruction(8,3,"Đun nước sôi trong nồi, cho cà chua vào nấu chín.");
//        dbHandler.addInstruction(8,4,"Khi cà chua đã mềm, cho hành tím và tỏi vào phi thơm.");
//        dbHandler.addInstruction(8,5,"Đập trứng vào tô, đánh tan và thêm 1 chút muối, tiêu.");
//        dbHandler.addInstruction(8,6,"Cho trứng vào nồi, khuấy đều và đun khoảng 2-3 phút cho trứng chín");
//        dbHandler.addInstruction(8,7,"Nêm thêm muối, đường, hạt nêm cho vừa ăn.");
//        dbHandler.addInstruction(9,1,"Rửa sạch thịt gà, cắt thành từng miếng nhỏ.");
//        dbHandler.addInstruction(9,2,"Rửa sạch lá giang, bỏ bớt cuống lá, cho vào nước sôi đun sôi khoảng 1 phút, để lá giang mềm và thơm hơn.");
//        dbHandler.addInstruction(9,3,"Băm hành tím nhỏ, cắt cà rốt thành những lát mỏng.");
//        dbHandler.addInstruction(9,4,"Đun nước sôi trong nồi, cho thịt gà vào nấu chín.");
//        dbHandler.addInstruction(9,5,"Sau đó, cho lá giang, hành tím và cà rốt vào nồi, đun sôi trong vài phút cho mềm.");
//        dbHandler.addInstruction(9,6,"Nêm muối, đường, hạt nêm, tiêu cho vừa ăn.");
//        dbHandler.addInstruction(10,1,"Rửa sạch bầu, thái thành miếng nhỏ");
//        dbHandler.addInstruction(10,2,"Rửa sạch hến, để ráo nước");
//        dbHandler.addInstruction(10,3,"Băm nhuyễn hành tím và tỏi.");
//        dbHandler.addInstruction(10,4,"Đun nước sôi trong nồi, cho bầu vào nấu chín.");
//        dbHandler.addInstruction(10,5,"Sau đó, cho hến vào nồi, đun sôi trong vài phút.");
//        dbHandler.addInstruction(10,6,"Phi hành tím và tỏi trong chảo, cho vào nồi canh.");
//        dbHandler.addInstruction(10,7,"Nêm muối, đường, hạt nêm, tiêu cho vừa ăn.");
    }
}